services:
  postgres-dev:
    image: postgres:16.8-alpine
    container_name: postgres-dev
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: minicrm
    volumes:
      - crm-data-dev:/var/lib/postgresql/data
    restart: 'always'

  postgres-test:
    image: postgres:16.8-alpine
    container_name: postgres-test
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: minicrm
    tmpfs:
      - /var/lib/postgresql/data:rw
    command:
      [
        'postgres',
        '-c',
        'fsync=off',
        '-c',
        'full_page_writes=off',
        '-c',
        'synchronous_commit=off',
      ]
    restart: 'no'

volumes:
  crm-data-dev:
